/**
 * Post-build script that wraps the Astro-generated Cloudflare worker
 * with content-negotiation logic for Accept: text/markdown.
 *
 * This provides a custom fallback for Markdown for Agents. For the
 * native Cloudflare feature, enable "Markdown for Agents" in the
 * Cloudflare dashboard (AI Crawl Control) or via the API:
 * PATCH /zones/{zone_id}/settings/content_converter
 * {"value": "on"}
 *
 * When native conversion is enabled, Cloudflare handles this at the
 * edge before the worker runs, so this wrapper becomes a no-op fallback.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const workerDir = path.resolve(__dirname, '../dist/_worker.js')
const originalFile = path.join(workerDir, 'index.js')
const wrappedFile = path.join(workerDir, '_astro-worker.js')

if (!fs.existsSync(originalFile)) {
  console.error('Worker entry not found:', originalFile)
  process.exit(1)
}

// Rename the original worker entry so we can wrap it
fs.renameSync(originalFile, wrappedFile)

const wrapper = `// Auto-generated by scripts/wrap-worker.js — wraps Astro worker with markdown negotiation
import astroWorker from './_astro-worker.js'

export default {
  async fetch(request, env, ctx) {
    const accept = request.headers.get('Accept') || ''
    if (accept.includes('text/markdown')) {
      const url = new URL(request.url)
      let mdPath
      if (url.pathname === '/') {
        mdPath = '/index.md'
      } else if (url.pathname.endsWith('/')) {
        mdPath = url.pathname + 'index.md'
      } else {
        mdPath = url.pathname + '.md'
      }

      const mdRequest = new Request(new URL(mdPath, request.url), request)
      const mdResponse = await env.ASSETS.fetch(mdRequest)
      if (mdResponse.status === 200) {
        const body = await mdResponse.text()
        const tokenCount = Math.round(body.split(/\\s+/).filter(Boolean).length * 1.3)
        const headers = new Headers(mdResponse.headers)
        headers.set('Content-Type', 'text/markdown; charset=utf-8')
        headers.set('Vary', 'Accept')
        headers.set('Content-Signal', 'ai-train=yes, search=yes, ai-input=yes')
        headers.set('X-Markdown-Tokens', String(tokenCount))
        return new Response(body, { status: 200, headers })
      }
    }
    return astroWorker.fetch(request, env, ctx)
  }
}
`

fs.writeFileSync(originalFile, wrapper, 'utf-8')
console.log('Wrapped Astro worker with markdown negotiation.')
