/**
 * Post-build script that wraps the Astro-generated Cloudflare worker
 * with content-negotiation logic for Accept: text/markdown.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const workerDir = path.resolve(__dirname, '../dist/_worker.js')
const originalFile = path.join(workerDir, 'index.js')
const wrappedFile = path.join(workerDir, '_astro-worker.js')

if (!fs.existsSync(originalFile)) {
  console.error('Worker entry not found:', originalFile)
  process.exit(1)
}

// Rename the original worker entry so we can wrap it
fs.renameSync(originalFile, wrappedFile)

const wrapper = `// Auto-generated by scripts/wrap-worker.js — wraps Astro worker with markdown negotiation
import astroWorker from './_astro-worker.js'

export default {
  async fetch(request, env, ctx) {
    const accept = request.headers.get('Accept') || ''
    if (accept.includes('text/markdown')) {
      const url = new URL(request.url)
      let mdPath
      if (url.pathname === '/') {
        mdPath = '/index.md'
      } else if (url.pathname.endsWith('/')) {
        mdPath = url.pathname + 'index.md'
      } else {
        mdPath = url.pathname + '.md'
      }

      const mdRequest = new Request(new URL(mdPath, request.url), request)
      const mdResponse = await env.ASSETS.fetch(mdRequest)
      if (mdResponse.status === 200) {
        const headers = new Headers(mdResponse.headers)
        headers.set('Content-Type', 'text/markdown; charset=utf-8')
        headers.set('Vary', 'Accept')
        return new Response(mdResponse.body, { status: 200, headers })
      }
    }
    return astroWorker.fetch(request, env, ctx)
  }
}
`

fs.writeFileSync(originalFile, wrapper, 'utf-8')
console.log('Wrapped Astro worker with markdown negotiation.')
